syntax = "proto3";

package aiserver.v1;

import "aiserver_v1_utils.proto";


message ChooseCodeReferencesRequest {
  string index_id = 1;
  oneof request {
    .aiserver.v1.ChooseCodeReferencesRequest.FileRequest file = 2;
    .aiserver.v1.ChooseCodeReferencesRequest.NodeRequest node = 3;
  }
  bool recompute = 4;

  message FileRequest {
    string file_id = 1;
  }

  message NodeRequest {
    string node_id = 1;
  }
}

message ChooseCodeReferencesResponse {
  oneof response {
    .aiserver.v1.ChooseCodeReferencesResponse.FileResponse file = 1;
    .aiserver.v1.ChooseCodeReferencesResponse.NodeResponse node = 2;
  }

  message FileResponse {
    string file_id = 1;
    repeated .aiserver.v1.ChooseCodeReferencesResponse.NodeResponse node_responses = 2;
  }

  message NodeResponse {
    string node_id = 1;
    repeated .aiserver.v1.CodeSymbolWithAction actions = 2;
    bool skipped = 3;
    repeated string dependencies = 4;
  }
}

message CodeSnippet {
  int32 start_line_number = 1;
  int32 end_line_number = 2;
  repeated string lines = 3;
}

message CodeSymbolWithAction {
  string workspace_relative_path = 1;
  int32 line_number = 2;
  int32 symbol_start_column = 3;
  int32 symbol_end_column = 4;
  .aiserver.v1.CodeSymbolWithAction.CodeSymbolAction action = 5;
  string symbol = 6;

  enum CodeSymbolAction {
    CODE_SYMBOL_ACTION_UNSPECIFIED = 0;
    CODE_SYMBOL_ACTION_GO_TO_DEFINITION = 1;
    CODE_SYMBOL_ACTION_GO_TO_IMPLEMENTATION = 2;
    CODE_SYMBOL_ACTION_REFERENCES = 3;
  }
}

message ComputeIndexTopoSortRequest {
  string index_id = 1;
}

message ComputeIndexTopoSortResponse {
}

message CreateExperimentalIndexRequest {
  repeated string files = 1;
  string target_dir = 2;
  string repo = 3;
}

message CreateExperimentalIndexResponse {
  string index_id = 1;
}

message ExtractPathsRequest {
  .aiserver.v1.FileCodeSnippets file_code_snippets = 1;
}

message ExtractPathsResponse {
  repeated .aiserver.v1.CodeSymbolWithAction paths = 1;
}

message FileCodeSnippets {
  string relative_workspace_path = 1;
  int32 total_lines = 2;
  repeated .aiserver.v1.CodeSnippet snippets = 3;
}

message IndexFileData {
  string index_id = 1;
  string workspace_relative_path = 2;
  string stage = 3;
  int32 order = 4;
  repeated .aiserver.v1.IndexFileData.NodeData nodes = 5;

  message NodeData {
    string node_id = 1;
    string stage = 2;
    string content = 3;
    string summary = 4;
  }
}

message ListExperimentalIndexFilesRequest {
  string index_id = 1;
}

message ListExperimentalIndexFilesResponse {
  string index_id = 1;
  repeated .aiserver.v1.IndexFileData files = 2;
}

message ListenExperimentalIndexRequest {
  string index_id = 1;
}

message ListenExperimentalIndexResponse {
  string index_id = 1;
  oneof item {
    .aiserver.v1.ListenExperimentalIndexResponse.ReadyItem ready = 2;
    .aiserver.v1.ListenExperimentalIndexResponse.RegisterItem register = 3;
    .aiserver.v1.ListenExperimentalIndexResponse.ChooseItem choose = 4;
    .aiserver.v1.ListenExperimentalIndexResponse.SummarizeItem summarize = 5;
    .aiserver.v1.ListenExperimentalIndexResponse.ErrorItem error = 6;
  }

  message ChooseItem {
    .aiserver.v1.ChooseCodeReferencesResponse response = 1;
    .aiserver.v1.ChooseCodeReferencesRequest request = 2;
    string req_uuid = 3;
  }

  message ErrorItem {
    string message = 1;
    int32 status_code = 2;
    oneof request {
      .aiserver.v1.RegisterFileToIndexRequest register = 3;
      .aiserver.v1.ChooseCodeReferencesRequest choose = 4;
      .aiserver.v1.SummarizeWithReferencesRequest summarize = 5;
    }
    string req_uuid = 6;
  }

  message ReadyItem {
    string index_id = 1;
    .aiserver.v1.ListenExperimentalIndexRequest request = 2;
  }

  message RegisterItem {
    .aiserver.v1.RegisterFileToIndexResponse response = 1;
    .aiserver.v1.RegisterFileToIndexRequest request = 2;
    string req_uuid = 3;
  }

  message SummarizeItem {
    .aiserver.v1.SummarizeWithReferencesResponse response = 1;
    .aiserver.v1.SummarizeWithReferencesRequest request = 2;
    string req_uuid = 3;
  }
}

message ReflectionData {
  string index_id = 1;
  string id = 2;
  string summary = 3;
}

message RegisterCodeReferencesRequest {
  string node_id = 1;
  repeated .aiserver.v1.SymbolActionResults references = 2;
}

message RegisterCodeReferencesResponse {
  repeated string dependencies = 1;
}

message RegisterFileToIndexRequest {
  string index_id = 1;
  string workspace_relative_path = 2;
  .aiserver.v1.SerializedContextNode root_context_node = 3;
  repeated string content = 4;
}

message RegisterFileToIndexResponse {
  string file_id = 1;
  string root_context_node_id = 2;
  repeated .aiserver.v1.URIResolutionAttempt dependency_resolution_attempts = 3;
  .aiserver.v1.IndexFileData file_data = 4;
}

message RequestReceivedResponse {
  string req_uuid = 1;
}

message SerializedContextNode {
  string workspace_relative_path = 1;
  int32 start_line_number = 2;
  int32 end_line_number = 3;
  repeated .aiserver.v1.SerializedContextNode children = 4;
  .aiserver.v1.FileCodeSnippets node_snippets = 5;
}

message SetupIndexDependenciesRequest {
  string index_id = 1;
  string file_id = 3;
  repeated .aiserver.v1.URIResolutionResult dependency_resolution_results = 2;
}

message SetupIndexDependenciesResponse {
}

message SummarizeWithReferencesRequest {
  string index_id = 1;
  string node_id = 2;
  bool recompute = 3;
}

message SummarizeWithReferencesResponse {
  oneof response {
    .aiserver.v1.SummarizeWithReferencesResponse.Success success = 1;
    .aiserver.v1.SummarizeWithReferencesResponse.Dependency dependency = 2;
  }
  string node_id = 3;

  message Dependency {
    repeated string nodes = 2;
  }

  message Success {
    string summary = 1;
  }
}

message SymbolActionResultReference {
  .aiserver.v1.SimpleRange range = 1;
  .aiserver.v1.FileCodeSnippets reference = 2;
}

message SymbolActionResults {
  .aiserver.v1.CodeSymbolWithAction action = 1;
  repeated .aiserver.v1.SymbolActionResultReference references = 2;
}

message URIResolutionAttempt {
  string workspace_relative_path = 1;
  string node_id = 2;
  .aiserver.v1.CodeSymbolWithAction symbol = 3;
}

message URIResolutionResult {
  .aiserver.v1.URIResolutionAttempt request = 1;
  repeated string resolved_paths = 2;
}
